### ISSUE TITLE
[Feature Request] Add icons for .3FR, .B64, .BAY, .BMP, .CR2, .CR3, .CRW, .EXIF and .QOI, 

### ISSUE THREAD

**Issue by NaiveInvestigator** [xmha97/IGExtIcons#1]
Please do add them whenever you can! Love your icon set!

Edit: Btw can we add instructions too on how to install the set. I think it will help a lot of ppl who are new.

**Comment by xmha97** [comment]
All of these requested icons are now available.
You can also contribute to this project by adding instructions.

**Comment by NaiveInvestigator** [comment]
> All of these requested icons are now available.

Oh lol the icons was in the repository. Could we add those icons in a new release for less confusion since it doesn't have include the others? 

> You can also contribute to this project by adding instructions.

Sure! Will also add instructions soon!

**Comment by xmha97** [comment]
> Could we add those icons in a new release for less confusion since it doesn't include the others?

Yes
